version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - docker.env
    networks:
      - postgres
      - pg-server

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - postgres

  backend:
    container_name: apiblogmcpeblocker
    image: apiblogmcpeblocker
    build:
      context: .
    command: npm run start:prod
    env_file:
      - .env
    ports:
      - 5555:5555
      - 9229:9229
      - 9230:9230
    networks:
      - pg-server
    volumes:
      - ./src:/app/src:ro
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./node_modules:/app/node_modules:ro
    depends_on:
      - postgres

networks:
  postgres:
    driver: bridge
  pg-server: