version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test
      - add_ssh_keys
      - run:
          name: Access to server
          command: ssh root@mcpeblocker.uz
      - run:
          name: Locate the project
          command: cd ~/Projects/api.blog.mcpeblocker.uz
      - run:
          name: Pull from repository
          command: git pull
      - run:
          name: Restart pm2 process
          command: pm2 restart "api.blog.mcpeblocker.uz"
workflows:
  build-and-test:
    jobs:
      - build-and-test